### PR TITLE
create custom router for Multistore

### PR DESCRIPTION
**Pull request by TigerWhite1**
Hi,

I create a custom router to manage mutli store as on magento 2.

If we activate the multistore on view store front it will add a `storeCode=en` parameter.

VueStoreFront Api will convert `storeCode=en` in `{url-magento}/vsbridge/{store-code}/{controller}/{action}`

Magento 1 does not support adding store code in the url.

With the custom router it is now possible as on Magento 2.

Example :

- `{url-magento}/vsbridge/{controller}/{action}` => default store
- `{url-magento}/vsbridge/en/{controller}/{action}`  => store en

Thanks.

### CODE REVIEW

**Comment by TigerWhite1** [comment]
Up :)

**Comment by pkarw** [comment]
Looks OK, however I'm not a Magento expert we need some @sandermangel or @afirlejczyk expertise in here

**Comment by sandermangel** [comment]
Hi @TigerWhite1,
under `System > Config > Web > Add Store Code to URLs` storecodes can be added to URLs. 
Wouldn't that create a conflict with this feature?

**Comment by nhp** [comment]
This looks to just rebuild a feature already available. If there is more to it I would like to understand what it is as we are using the multistore stuff and happened to have problems with it in the beginning as we did not want to have it added but to have it done on a subdomain base.

**Comment by TigerWhite1** [comment]
Hi @sandermangel  @nhp,

Thanks for your feedback. 

Actually with the option it's good and with the updated view strorefront api everything works well now.

we can close

Thanks

**Pull request closed without merging**
