### PR TITLE
Generating mapping from magento attribute data

### PR DESCRIPTION
**Pull request by VladimirPlastovets**
Added generating elasticsearch product mapping from attribute data in magento instead of generating it dynamically.

### CODE REVIEW

**Comment by pkarw** [comment]
Cool staff! https://github.com/DivanteLtd/vue-storefront/issues/1726

**Comment by pkarw** [comment]
@VladimirPlastovets could You please just solve the conflicts?

**Comment by VladimirPlastovets** [comment]
@pkarw done

**Comment by VladimirPlastovets** [comment]
@pkarw could you please review my changes and merge it if all okay for you, to prevent additional conflicts, because i started developing supporting cms features for magento 1 module. Thanks!

**Comment by pkarw** [comment]
Oh, sorry I've missed this PR somehow :)

**Comment by pkarw** [comment]
By the way: https://github.com/DivanteLtd/vue-storefront/issues/1726 :-)

**Pull request merged**
