### PR TITLE
Add mapper to fit response with needed schema

### PR DESCRIPTION
**Pull request by mtarld**
Add mapper in order to be able to format response according to VSF required schema.
In order to resolve: https://github.com/DivanteLtd/magento1-vsbridge/issues/24

### CODE REVIEW

**Comment by pkarw** [comment]
I think that the best person to review this mappers is @afirlejczyk

**Comment by nhp** [comment]
Shouldn't there be at least some kind of possibility to then add custom attributes to the cast maps? Or is this then left to the user to override?

**Comment by cewald** [comment]
Is there work in progress?
I ran into this problem with german postcodes which could contain a leading zero.
It obviously won't work without a specific mapping.

**Comment by cewald** [comment]
> Shouldn't there be at least some kind of possibility to then add custom attributes to the cast maps? Or is this then left to the user to override?

You could easily use the Magento module system to overwrite a mapper classes you need to extend.

**Comment by cewald** [comment]
@sandermangel @nhp I added an updated version of this PR (#49) with an approach to extend the mapping without class overwrites. It works like in the `DivanteLtd/magento1-vsbridge-indexer` and its custom data-sources.

**Pull request closed without merging**
